name: auto clean

on:
  #schedule:
  #  - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 3
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
