name: Build OpenWrt

on:
  release:
    types: [published]
  watch:
    types: [started]
#  schedule:
#  - cron: 0 8 * * 5

env:
  REPO_URL: https://github.com/sdf8057/ipq6000
  REPO_BRANCH: master
  CONFIG_FILE: zn-m2.config
  UPLOAD_FIRMWARE: true
  UPLOAD_PACKAGES: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
        rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo apt -y autoremove --purge
        sudo apt clean

    - name: Clone source code
      run: |
        echo -e "$(nproc) thread compile"
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate configuration file
      run: |
        cp -f $CONFIG_FILE openwrt/.config
        cd openwrt
        make defconfig
          
    - name: Download package
      run: |
        cd openwrt
        make download -j8 || make download -j1 V=s
        rm -rf $(find dl -size -1024c)

    - name: Compile the firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 || make -j1 V=s

    - name: Organize files
      run: |
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        cd openwrt
        mkdir -p artifact/firmware
        mkdir -p artifact/packages
        rm -rf $(find bin/targets/ -type d -name "packages")
        cp -rf $(find bin/targets/ -type f) artifact/firmware/
        cp -rf $(find bin/packages/ -type f -name "*.ipk") artifact/packages/
        
    - name: Upload firmware
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true'
      with:
        name: OpenWrt_firmware
        path: openwrt/artifact/firmware
    
    - name: Upload packages
      uses: actions/upload-artifact@main
      if: env.UPLOAD_PACKAGES == 'true'
      with:
        name: OpenWrt_packages
        path: openwrt/artifact/packages
